'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import { RecoilRoot } from 'recoil'
import MyProviders from '@/components/MyProviders'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, session }) {
  console.log('session', session)
  return (
    <html lang="en">
      <body className={inter.className}>
        <MyProviders session={session}>
          {children}
        </MyProviders>
        </body>
    </html>
  )
}
